# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-19 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20171116_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='code_samples',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='code_samples',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
